---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mediaserver
  namespace: dev
  #  annotations:
  #    fluxcd.io/automated: "true"
spec:
  releaseName: mediaserver
  chart:
    git: git@github.com:tounefr/helm-operator-get-started
    path: charts/mediaserver
    ref: master
