---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mediaserver
  namespace: dev
spec:
  releaseName: mediaserver
  targetNamespace: dev
  chart:
    git: git@github.com:tounefr/helm-operator-get-started
    path: charts/mediaserver
    ref: master
  values:
    replicas: 1
