version: '2'
volumes:
  downloads:
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    ports:
     - 32400:32400
    environment:
     - PUID=1000
     - PGID=1000
     - VERSION=docker
     - UMASK_SET=022 #optional
#     - PLEX_CLAIM=claim-RXrnaC-yySC82BkRHSCT
    volumes:
            #     - /config
     - downloads:/tv
     - downloads:/movies
#    restart: unless-stopped
    labels:
      kompose.service.expose: "plex"
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
     - PUID=1000
     - PGID=1000
     - TZ=Europe/Paris
     #- TRANSMISSION_WEB_HOME=/combustion-release/ #optional
     #- USER=username #optional
     #- PASS=password #optional
    volumes:
      - /config
      - downloads:/downloads
      - downloads:/tv
      - /watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    labels:
      kompose.service.expose: "transmission"
#    restart: unless-stopped

