# 1 "charts/mediaserver/templates/downloads-persistentvolumeclaim.yaml"
# 1 "<built-in>"
# 1 "<command-line>"
# 31 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 32 "<command-line>" 2
# 1 "charts/mediaserver/templates/downloads-persistentvolumeclaim.yaml"
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
  name: plex-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
