apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f mediaserver.yml -c -o mediaserver
    kompose.service.expose: plex
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: plex
  name: plex
spec:
  ports:
  - name: "32400"
    port: 32400
    targetPort: 32400
  selector:
    io.kompose.service: plex
status:
  loadBalancer: {}
