apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f mediaserver.yml -c -o mediaserver
    kompose.service.expose: plex
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: plex
  name: plex
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: plex
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: UMASK_SET
          value: "022"
        - name: VERSION
          value: docker
        image: linuxserver/plex:latest
        name: plex
        ports:
        - containerPort: 32400
        resources: {}
        volumeMounts:
        - mountPath: /tv
          name: downloads
        - mountPath: /movies
          name: downloads
        - mountPath: /config
          name: config
      restartPolicy: Always
      volumes:
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads
      - name: plex-config
        persistentVolumeClaim:
          claimName: plex-config
status: {}
