---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f mediaserver.yml -c -o mediaserver
    kompose.service.expose: transmission
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp:
  labels:
    io.kompose.service: transmission
  name: transmission
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp:
      labels:
        io.kompose.service: transmission
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: Europe/Paris
        image: linuxserver/transmission:latest
        name: transmission
        ports:
        - containerPort: 9091
        - containerPort: 51413
        - containerPort: 51413
          protocol: UDP
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: transmission-configmap
        - mountPath: /downloads
          name: downloads
        - mountPath: /watch
          name: transmission-claim2
      restartPolicy: Always
      volumes:
      - name: transmission-configmap
        configMap:
          name: transmission-config
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads
      - name: transmission-claim2
        persistentVolumeClaim:
          claimName: transmission-claim2
status: {}
