apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: plex
  name: plex
spec:
  rules:
  - host: plex
    http:
      paths:
      - backend:
          serviceName: plex
          servicePort: 32400
status:
  loadBalancer: {}
